### ISSUE TITLE
Scrapbook autosave - save unfinish page

### ISSUE THREAD

**Issue by ghost** [danny0838/firefox-scrapbook-autosave#3]
I try auto save webpage with much JS and full load page is about 5 second 

Is possible wait for finish (for example wait for DIV with ID=....) 

Is possible ?

**Comment by danny0838** [comment]
It it possible but might not be viable to support a more complicated cases. We implemented an option to delay for a customizable seconds before capture in 1.4.3 instead.

**Comment by ghost** [comment]
Before 1.4.3  I created small fix in source code ;)

```

//code before the pause
setTimeout(function(){
    //do what you need here
    sbContentSaver.captureWindow(....
}, 5000);
```

But delay , 
not solve the problem 100%
sometimes page load time is long 5s and autosave save not complete page :(
